[tool.poetry]
name = "misspy"
version = "2023.08.27.dev1"
description = "Misskey API library for Python with StreamingAPI support."
authors = ["sonyakun <misspy@sonyakun.xyz>"]
packages = [{include = "misspy"}]
readme = "README.md"
documentation = "https://misspy.sonyakun.xyz/en"
repository = "https://github.com/sonyakun/misspy"

[tool.poetry.dependencies]
python = "^3.8"
httpx = ">=0.24.1,<0.26.0"
websockets = "^11.0.3"
attrdictionary = "^1.0.0"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
