[tool.poetry]
name = "misspy"
version = "2023.08.25.pre1"
description = ""
authors = ["sonyakun <contact@sonyakun.xyz>"]
packages = [{include = "misspy"}]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.11"
httpx = "^0.24.1"
websockets = "^11.0.3"
attrdictionary = "^1.0.0"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"